#!/usr/bin/env python3
"""
ESEE 2026 Degrowth ABM Project - Setup and Validation Script

This script:
1. Checks Python version (needs 3.11+)
2. Checks if running on M4 Mac (Apple Silicon)
3. Lists all required packages
4. Creates/updates requirements.txt
5. Validates project folder structure
6. Provides instructions for virtual environment setup
"""

import sys
import platform
import os
from pathlib import Path
from typing import List, Tuple

# Required packages with versions
REQUIRED_PACKAGES = [
    "pandas==2.1.0",
    "numpy==1.24.0",
    "scikit-learn==1.3.0",
    "econml==0.14.0",  # for causal forest
    "mesa==3.2.0",  # for ABM
    "matplotlib==3.7.0",
    "seaborn==0.12.0",
    "scipy==1.11.0",
    "pyyaml==6.0",
    "pytest==7.4.0",
]

# Expected folder structure
EXPECTED_FOLDERS = [
    "data/raw",
    "data/processed",
    "results/figures",
    "results/tables",
    "results/model_outputs",
    "results/logs",
    "src/utils",
    "tests",
    "paper",
    "config",
    "notebooks",
]

# Expected key files
EXPECTED_FILES = [
    "ESEE2026_PROJECT_CONTEXT.md",
    "DEVELOPMENT_ROADMAP.md",
    "QUICK_START_GUIDE.md",
]


def check_python_version() -> Tuple[bool, str]:
    """Check if Python version is 3.11 or higher."""
    version = sys.version_info
    version_string = f"{version.major}.{version.minor}.{version.micro}"
    
    if version.major == 3 and version.minor >= 11:
        return True, version_string
    elif version.major == 3 and version.minor < 11:
        return False, version_string
    else:
        return False, version_string


def check_apple_silicon() -> Tuple[bool, str]:
    """Check if running on Apple Silicon (M4 Mac or other M-series)."""
    system = platform.system()
    machine = platform.machine()
    
    if system == "Darwin" and machine == "arm64":
        # Check for M-series chip
        processor = platform.processor()
        if "arm" in processor.lower() or machine == "arm64":
            return True, f"Apple Silicon ({machine})"
    elif system == "Darwin":
        return False, f"macOS on {machine} (not Apple Silicon)"
    else:
        return False, f"{system} on {machine}"


def create_requirements_txt(project_root: Path) -> None:
    """Create or update requirements.txt with required packages."""
    requirements_path = project_root / "requirements.txt"
    
    try:
        with open(requirements_path, "w") as f:
            f.write("# ESEE 2026 Degrowth ABM Project - Python Dependencies\n")
            f.write("# Generated by src/00_setup.py\n\n")
            for package in REQUIRED_PACKAGES:
                f.write(f"{package}\n")
        print(f"✓ Created/updated {requirements_path}")
    except Exception as e:
        print(f"✗ Error creating requirements.txt: {e}")
        raise


def validate_folder_structure(project_root: Path) -> Tuple[bool, List[str]]:
    """Validate that all expected folders exist."""
    missing_folders = []
    
    for folder in EXPECTED_FOLDERS:
        folder_path = project_root / folder
        if not folder_path.exists():
            missing_folders.append(folder)
        elif not folder_path.is_dir():
            missing_folders.append(f"{folder} (exists but is not a directory)")
    
    return len(missing_folders) == 0, missing_folders


def validate_key_files(project_root: Path) -> Tuple[bool, List[str]]:
    """Validate that key context files exist."""
    missing_files = []
    
    for file in EXPECTED_FILES:
        file_path = project_root / file
        if not file_path.exists():
            missing_files.append(file)
    
    return len(missing_files) == 0, missing_files


def print_instructions():
    """Print instructions for virtual environment setup."""
    print("\n" + "="*70)
    print("NEXT STEPS: Create Virtual Environment")
    print("="*70)
    print("\n1. Create virtual environment:")
    print("   python -m venv venv")
    print("\n2. Activate virtual environment:")
    print("   source venv/bin/activate  # On macOS/Linux")
    print("   venv\\Scripts\\activate     # On Windows")
    print("\n3. Upgrade pip:")
    print("   pip install --upgrade pip")
    print("\n4. Install packages (on M4 Mac, use --break-system-packages if needed):")
    print("   pip install -r requirements.txt")
    print("   # OR if needed:")
    print("   pip install -r requirements.txt --break-system-packages")
    print("\n5. Or use the provided setup script:")
    print("   chmod +x setup_env.sh")
    print("   ./setup_env.sh")
    print("\n" + "="*70 + "\n")


def main():
    """Main setup and validation function."""
    print("="*70)
    print("ESEE 2026 Degrowth ABM Project - Setup & Validation")
    print("="*70)
    print()
    
    # Get project root (parent of src/)
    project_root = Path(__file__).parent.parent.absolute()
    print(f"Project root: {project_root}")
    print()
    
    # 1. Check Python version
    print("1. Checking Python version...")
    version_ok, version_str = check_python_version()
    if version_ok:
        print(f"   ✓ Python {version_str} (3.11+ required)")
    else:
        print(f"   ✗ Python {version_str} - WARNING: Python 3.11+ recommended")
        print("     Some packages may not work correctly with older versions.")
    print()
    
    # 2. Check for Apple Silicon
    print("2. Checking system architecture...")
    is_apple_silicon, arch_info = check_apple_silicon()
    print(f"   System: {arch_info}")
    if is_apple_silicon:
        print("   ✓ Running on Apple Silicon - may need --break-system-packages flag")
    print()
    
    # 3. List required packages
    print("3. Required packages:")
    for i, package in enumerate(REQUIRED_PACKAGES, 1):
        print(f"   {i:2d}. {package}")
    print()
    
    # 4. Create requirements.txt
    print("4. Creating requirements.txt...")
    try:
        create_requirements_txt(project_root)
    except Exception as e:
        print(f"   ✗ Failed: {e}")
        sys.exit(1)
    print()
    
    # 5. Validate folder structure
    print("5. Validating folder structure...")
    folders_ok, missing_folders = validate_folder_structure(project_root)
    if folders_ok:
        print(f"   ✓ All {len(EXPECTED_FOLDERS)} expected folders exist")
    else:
        print(f"   ✗ Missing {len(missing_folders)} folder(s):")
        for folder in missing_folders:
            print(f"      - {folder}")
        print("\n   Run this command to create missing folders:")
        print("   mkdir -p " + " ".join(missing_folders))
    print()
    
    # 6. Validate key files
    print("6. Validating key context files...")
    files_ok, missing_files = validate_key_files(project_root)
    if files_ok:
        print(f"   ✓ All {len(EXPECTED_FILES)} context files present")
    else:
        print(f"   ✗ Missing {len(missing_files)} file(s):")
        for file in missing_files:
            print(f"      - {file}")
    print()
    
    # Summary
    print("="*70)
    if version_ok and folders_ok and files_ok:
        print("✓ SETUP VALIDATION PASSED")
    else:
        print("⚠ SETUP VALIDATION HAD WARNINGS (see above)")
    print("="*70)
    
    # Print instructions
    print_instructions()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nSetup interrupted by user.")
        sys.exit(1)
    except Exception as e:
        print(f"\n\n✗ Unexpected error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

